import { Inter } from "next/font/google";
import "@/app/globals.css";
import Logo from "@/components/Logos/Logo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex items-center justify-center">
          <Logo width="300" heigth="300" />
        </div>
        {children}
      </body>
    </html>
  );
}
